version: '3.8'

services:
  ocpi-validator:
    #build: .
    image: alickjoe/ocpi-validator:latest
    container_name: ocpi-validator
    ports:
      - "3002:3002"  # Map host port 8080 to container port 8080
    restart: unless-stopped
    networks:
      aznetwork:
        aliases:
          - ocpi-validator
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocpi-validator.rule=Host(`ocpi-validator.localhost`)"
      - "traefik.http.services.ocpi-validator.loadbalancer.server.port=3002"

networks:
  aznetwork:
    name: mynetwork
    external: true